version: "3.9"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  mongo:
    image: mongo:latest
    container_name: gift_mongo
    ports:
      - "27017:27017"
